<?php

require_once( get_template_directory() . '/includes/acf/torque-acf-search-class.php' );

class Everton_ACF {

  public function __construct() {
    add_action('admin_init', array( $this, 'acf_admin_init'), 99);
    add_action('acf/init', array( $this, 'acf_init' ) );

    // hide acf in admin - client doesnt need to see this
    // add_filter('acf/settings/show_admin', '__return_false');

    // add acf fields to wp search
    if ( class_exists( 'Torque_ACF_Search' ) ) {
      add_filter( Torque_ACF_Search::$ACF_SEARCHABLE_FIELDS_FILTER_HANDLE, array( $this, 'add_fields_to_search' ) );
    }
  }

  public function acf_admin_init() {
    // hide options page
    // remove_menu_page('acf-options');
  }

  public function add_fields_to_search( $fields ) {
    // $fields[] = 'custom_field_name';
    return $fields;
  }

  public function acf_init() {
    // add content sections here
    if( function_exists('acf_add_local_field_group') ):

      acf_add_local_field_group(array(
        'key' => 'group_5f5c23955b158',
        'title' => 'Everton Options',
        'fields' => array(
          array(
            'key' => 'field_5f5c239bd9e3e',
            'label' => 'General',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5f5c23a7d9e3f',
            'label' => 'Address',
            'name' => 'address',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
          ),
          array(
            'key' => 'field_5f5c23e5c73e2',
            'label' => 'Phone',
            'name' => 'phone',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
          ),
          array(
            'key' => 'field_5f5c23f0c73e3',
            'label' => 'Email',
            'name' => 'email',
            'type' => 'email',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
          ),
          array(
            'key' => 'field_5f5e9af6d42dd',
            'label' => 'Social Channels',
            'name' => 'social_channels',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'table',
            'button_label' => 'Add Social Channel',
            'sub_fields' => array(
              array(
                'key' => 'field_5f5e9b5e52608',
                'label' => 'Icon',
                'name' => 'icon',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'choices' => array(
                  'fa-facebook' => 'Facebook',
                  'fa-instagram' => 'Instagram',
                ),
                'default_value' => array(
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
              ),
              array(
                'key' => 'field_5f5e9af6d42de',
                'label' => 'URL',
                'name' => 'url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
              ),
            ),
          ),
          array(
            'key' => 'field_5f5c2460770e9',
            'label' => 'Header',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5f5c2466770ea',
            'label' => 'Drawer Menu CTA',
            'name' => 'drawer_menu_cta',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'return_format' => 'array',
          ),
          array(
            'key' => 'field_5f5d9a39100c0',
            'label' => 'Footer',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'placement' => 'left',
            'endpoint' => 0,
          ),
          array(
            'key' => 'field_5f5d9a41100c1',
            'label' => 'Office Hours',
            'name' => 'office_hours',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'collapsed' => '',
            'min' => 0,
            'max' => 0,
            'layout' => 'row',
            'button_label' => 'Add hours',
            'sub_fields' => array(
              array(
                'key' => 'field_5f5d9b3e100c2',
                'label' => 'Details',
                'name' => 'details',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                  'width' => '',
                  'class' => '',
                  'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'M-F: 7am-6pm',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
              ),
            ),
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'options_page',
              'operator' => '==',
              'value' => 'acf-options',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5f5d81fe484a1',
        'title' => 'Header Module',
        'fields' => array(
          array(
            'key' => 'field_5f5d8208da691',
            'label' => 'Enable Hero?',
            'name' => 'enable_hero',
            'type' => 'true_false',
            'instructions' => 'If enabled, set the Featured Image in the module provided to the right.',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
          array(
            'key' => 'field_5f5fe494a2fac',
            'label' => 'Slimline Hero?',
            'name' => 'slimline_hero',
            'type' => 'true_false',
            'instructions' => 'If set to \'Yes\' the hero image will be reduced in height.',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_5f5d8208da691',
                  'operator' => '==',
                  'value' => '1',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
          ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      acf_add_local_field_group(array(
        'key' => 'group_5f5da4c702868',
        'title' => 'Content Modules',
        'fields' => array(
          array(
            'key' => 'field_5f5da4cbfdcd1',
            'label' => 'Content Modules',
            'name' => 'content_modules',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'layouts' => array(
              'layout_5f5effee1f5cb' => array(
                'key' => 'layout_5f5effee1f5cb',
                'name' => 'title_content_cta_image',
                'label' => 'Title, Content, CTA & Image',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f5f00051f5cc',
                    'label' => 'Alignment',
                    'name' => 'alignment',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Content left, image right',
                      'right' => 'Content right, image left',
                    ),
                    'default_value' => array(
                      0 => 'left',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5f5f00351f5cd',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5f5f003a1f5ce',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                  ),
                  array(
                    'key' => 'field_5f5f004e1f5cf',
                    'label' => 'CTA',
                    'name' => 'cta',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_5f5f00581f5d0',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5f60a257ccbd8' => array(
                'key' => 'layout_5f60a257ccbd8',
                'name' => 'title_content',
                'label' => 'Title & Content',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f60a257ccbda',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5f60a257ccbdb',
                    'label' => 'Content',
                    'name' => 'content',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                  ),
                  array(
                    'key' => 'field_5f60a257ccbd9',
                    'label' => 'Bottom Border?',
                    'name' => 'bottom_border',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5f613387c2ebb' => array(
                'key' => 'layout_5f613387c2ebb',
                'name' => 'two_column_content',
                'label' => 'Two Column Content',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f6133a7c2ebc',
                    'label' => 'Column One',
                    'name' => 'column_one',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                  ),
                  array(
                    'key' => 'field_5f6133cac2ebd',
                    'label' => 'Column Two',
                    'name' => 'column_two',
                    'type' => 'wysiwyg',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'tabs' => 'all',
                    'toolbar' => 'full',
                    'media_upload' => 0,
                    'delay' => 0,
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5f6290d81c1ee' => array(
                'key' => 'layout_5f6290d81c1ee',
                'name' => 'gallery',
                'label' => 'Gallery',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f6290df1c1ef',
                    'label' => 'Gallery',
                    'name' => 'gallery',
                    'type' => 'post_object',
                    'instructions' => 'Add a Filtered Gallery from the main admin menu, and then select it here to display in the page content.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                      0 => 'tq_filtered_gallery',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5f63d81edf78d' => array(
                'key' => 'layout_5f63d81edf78d',
                'name' => 'gallery_w_captions',
                'label' => 'Gallery w/ Captions',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f63d81edf78e',
                    'label' => 'Gallery w/ Captions',
                    'name' => 'gallery_w_captions',
                    'type' => 'post_object',
                    'instructions' => 'Add a Filtered Gallery from the main admin menu, and then select it here to display in the page content.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '',
                      'class' => '',
                      'id' => '',
                    ),
                    'post_type' => array(
                      0 => 'tq_filtered_gallery',
                    ),
                    'taxonomy' => array(
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'return_format' => 'id',
                    'ui' => 1,
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              '5f5da4f5cf2ef' => array(
                'key' => '5f5da4f5cf2ef',
                'name' => 'cta_banner',
                'label' => 'CTA Banner',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f5feb738c018',
                    'label' => 'Alignment',
                    'name' => 'alignment',
                    'type' => 'select',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '33.33',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'left' => 'Content left, image right',
                      'right' => 'Content right, image left',
                    ),
                    'default_value' => array(
                      0 => 'left',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5f5fed95d97c9',
                    'label' => 'Contain Image?',
                    'name' => 'contain_image',
                    'type' => 'true_false',
                    'instructions' => 'Set to \'Yes\' to restrict image to the container height & width and maintain the image aspect ratio, otherwise the image will fill the container.',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '33.33',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_5f5feba88c019',
                    'label' => 'Offset Image?',
                    'name' => 'offset_image',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                      array(
                        array(
                          'field' => 'field_5f5fed95d97c9',
                          'operator' => '==',
                          'value' => '1',
                        ),
                      ),
                    ),
                    'wrapper' => array(
                      'width' => '33.33',
                      'class' => '',
                      'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                  ),
                  array(
                    'key' => 'field_5f5da4fafdcd2',
                    'label' => 'Title',
                    'name' => 'title',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '100',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                  ),
                  array(
                    'key' => 'field_5f5da50afdcd4',
                    'label' => 'Button',
                    'name' => 'button',
                    'type' => 'link',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                  ),
                  array(
                    'key' => 'field_5f5da503fdcd3',
                    'label' => 'Image',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '50',
                      'class' => '',
                      'id' => '',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                    'min_width' => '',
                    'min_height' => '',
                    'min_size' => '',
                    'max_width' => '',
                    'max_height' => '',
                    'max_size' => '',
                    'mime_types' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
              'layout_5f5f00927d378' => array(
                'key' => 'layout_5f5f00927d378',
                'name' => 'content_spacer',
                'label' => 'Content Spacer',
                'display' => 'block',
                'sub_fields' => array(
                  array(
                    'key' => 'field_5f5f009b7d379',
                    'label' => 'Spacer Height',
                    'name' => 'spacer_height',
                    'type' => 'number',
                    'instructions' => 'Enter only a number, either negative or positive.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '30',
                      'class' => '',
                      'id' => '',
                    ),
                    'default_value' => 1,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                  ),
                  array(
                    'key' => 'field_5f5f01a27d37a',
                    'label' => 'Spacer Measurement',
                    'name' => 'spacer_measurement',
                    'type' => 'select',
                    'instructions' => 'Select measurement used to calculate spacer height.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '35',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'px' => 'Pixels (px)',
                      'vw' => 'Percentage of viewport width (vw)',
                      'vh' => 'Percentage of viewport height (vh)',
                      'em' => 'Relative to the font-size of the element (em)',
                    ),
                    'default_value' => array(
                      0 => 'em',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                  ),
                  array(
                    'key' => 'field_5f5f02497d37b',
                    'label' => 'Visibility',
                    'name' => 'visibility',
                    'type' => 'select',
                    'instructions' => 'Choose which devices you\'d like to display the spacer on.',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                      'width' => '35',
                      'class' => '',
                      'id' => '',
                    ),
                    'choices' => array(
                      'all_devices' => 'All Devices',
                      'mobile_only' => 'Mobile Only',
                      'tablet_only' => 'Tablet Only',
                      'desktop_only' => 'Desktop Only',
                      'mobile_tablet' => 'Mobile & Tablet',
                      'tablet_desktop' => 'Tablet & Desktop',
                    ),
                    'default_value' => array(
                      0 => 'all_devices',
                    ),
                    'allow_null' => 0,
                    'multiple' => 0,
                    'ui' => 1,
                    'ajax' => 0,
                    'return_format' => 'value',
                    'placeholder' => '',
                  ),
                ),
                'min' => '',
                'max' => '',
              ),
            ),
            'button_label' => 'Add Content Module',
            'min' => '',
            'max' => '',
          ),
        ),
        'location' => array(
          array(
            array(
              'param' => 'post_type',
              'operator' => '==',
              'value' => 'page',
            ),
          ),
        ),
        'menu_order' => 1,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
      ));
      
      endif;
  }
}

?>
